version: 2.1

# Define the jobs we want to run for this project
jobs:
  prepare:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: echo "prepare"
  build:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: echo "test"
  lint:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: echo "lint"
  publish:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: echo "publish"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - test
            - lint
      - publish:
          requires:
            - build
