#!/bin/sh

. "$CI_PROJECT_DIR/scripts/utils"

set -e
IFS=$'\n\t'

# function parse_arguments() {
#   read base
#   read base_version
#   printf -- "-f $Dockerfile " "$base"

#   while read image; do
#     read version
#     case "$image" in
#       dumb) dumb_version=$version ;;
#       *) exit 1;;
#     esac
#   done

#   templates -d=$dumb_version -b=$base -v=$base_version $CI_PROJECT_DIR/Dockerfile.template
# }

echo $CI_PROJECT_DIR
