#!/bin/sh

. "$CI_PROJECT_DIR/scripts/utils"

set -e
IFS=$'\n\t'

# function parse_arguments() {
#   read base
#   read base_version
#   printf -- "-f $Dockerfile " "$base"

#   while read image; do
#     read version
#     case "$image" in
#       dumb) dumb_version=$version ;;
#       *) exit 1;;
#     esac
#   done

#   templates -d=$dumb_version -b=$base -v=$base_version $CI_PROJECT_DIR/Dockerfile.template
# }

if [ -z $CI_PROJECT_DIR ];
then
  CI_PROJECT_DIR=$(pwd)
fi

# try to build docker images
exitCode=$($CI_PROJECT_DIR/scripts/pull-docker-image | tail -n 1)
echo $exitCode
# if [ $exitCode -eq "0" ]; then
#   echo "FOUND $CI_REGISTRY_IMAGE:$CI_JOB_NAME"; exit 0;
# fi

