#!/bin/bash

set -e
IFS=$'\n\t'

exitCode=$($CI_PROJECT_DIR/scripts/pull-docker-image | tail -n 1)
echo $exitCode

if [ $exitCode -eq "0" ]; then
  echo "FOUND $CI_REGISTRY_IMAGE:$CI_JOB_NAME"; exit 0;
fi

